// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRa2kznqMemJQrALREgDxcXA-tZuhgGz8',
    appId: '1:781049118078:web:517df83f622985beb9872f',
    messagingSenderId: '781049118078',
    projectId: 'shoeslymain',
    authDomain: 'shoeslymain.firebaseapp.com',
    storageBucket: 'shoeslymain.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMyNRIynQh3QeKuZ1_KCo_f31NoVLJTgc',
    appId: '1:781049118078:android:b8cd0af887364089b9872f',
    messagingSenderId: '781049118078',
    projectId: 'shoeslymain',
    storageBucket: 'shoeslymain.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMwJ_t8T5WdnTspNFIs14cXO8rXb0d0JQ',
    appId: '1:781049118078:ios:041574ab17d79e41b9872f',
    messagingSenderId: '781049118078',
    projectId: 'shoeslymain',
    storageBucket: 'shoeslymain.appspot.com',
    iosBundleId: 'com.example.shoeslymain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMwJ_t8T5WdnTspNFIs14cXO8rXb0d0JQ',
    appId: '1:781049118078:ios:041574ab17d79e41b9872f',
    messagingSenderId: '781049118078',
    projectId: 'shoeslymain',
    storageBucket: 'shoeslymain.appspot.com',
    iosBundleId: 'com.example.shoeslymain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRa2kznqMemJQrALREgDxcXA-tZuhgGz8',
    appId: '1:781049118078:web:d40031de7fe45e7fb9872f',
    messagingSenderId: '781049118078',
    projectId: 'shoeslymain',
    authDomain: 'shoeslymain.firebaseapp.com',
    storageBucket: 'shoeslymain.appspot.com',
  );
}
